#pragma once

#define VIAL_KEYBOARD_UID {0xF1, 0xB3, 0x4C, 0x68, 0x6C, 0x25, 0xF1, 0x53}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 5, 4 }

#define TAPPING_TERM 175
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#ifdef TAP_CODE_DELAY
#undef TAP_CODE_DELAY
#endif

#define TAP_CODE_DELAY 40
